version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    # Look for the configuration files (like pyproject.toml / requirements.txt) in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
